version: '3.2'

services:
    api:
        build: api
        container_name: piston_api
        cap_add:
            - CAP_SYS_ADMIN
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        environment:
            - PISTON_REPO_URL=https://github.com/yanjun-ios/piston/releases/download/Packages/index
            - PISTON_DISABLE_NETWORKING=false
            - PISTON_RUN_TIMEOUT=30000
        tmpfs:
            - /piston/jobs:exec,uid=1000,gid=1000,mode=711

    repo: # Local testing of packages
        build: repo
        container_name: piston_repo
        command: ['--no-build'] # Don't build anything
        volumes:
            - .:/piston
